version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      - aws ecr get-login-password  --region $CI_REGION	 | docker login --username AWS  --password-stdin $REPO_ARN
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "The commit hash is $COMMIT_HASH"
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    #    image: $REPO_URL:latest
    commands:
       - docker build -t $REPO_URL:latest .
       - docker tag $REPO_URL:latest $REPO_URL:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPO_URL:latest
      - docker push $REPO_URL:$IMAGE_TAG
      - echo Writing image definitions file...
      #- printf '{"ImageURI":"%s"}' $REPO_URL:$IMAGE_TAG > imageDetail.json
      - printf '[{"name":"web-graphs","imageUri":"%s"}]' $REPO_URL:$IMAGE_TAG > imagedefinitions.json
      # - pwd
artifacts:
  files:
    #- imageDetail.json
    - imagedefinitions.json
